import { YearInReviewPost } from "./types";

export const posts: YearInReviewPost[] = [
  // Dan Wang posts
  {
    id: "danwang-2025",
    url: "https://danwang.co/2025-letter/",
    year: 2025,
    author: "Dan Wang",
    title: "2025 Letter",
    preview:
      "Corgis, compute, Cold War; Ecclesiastes; ties; Stendhal; humor; Pascal's Wager; deep infrastructure; Germanic obedience; Texas State Fair",
    wordCount: 17358,
  },
  {
    id: "danwang-2023",
    url: "https://danwang.co/2023-letter/",
    year: 2023,
    author: "Dan Wang",
    title: "2023 Letter",
    preview:
      "A walk-and-talk; Crumb; running and tangping; Knausgaard; Elon as Palmer Eldritch; memelords; Chicago as a megacity; Norton; and a pause.",
    wordCount: 10865,
  },
  {
    id: "danwang-2022",
    url: "https://danwang.co/2022-letter/",
    year: 2022,
    author: "Dan Wang",
    title: "2022 Letter",
    preview:
      "Becoming a barbarian; an ideological revelry; lockdown; sweetgrass and banana leafs; crankiness; delightful animals; to the mountains",
    wordCount: 12400,
  },
  {
    id: "danwang-2021",
    url: "https://danwang.co/2021-letter/",
    year: 2021,
    author: "Dan Wang",
    title: "2021 Letter",
    preview:
      "Getting worse and getting better; Jesuits; common prosperity; Rossini's glittering realm; slow-casual chains; Lem's ocean; vowelsongs.",
    wordCount: 18734,
  },
  {
    id: "danwang-2020",
    url: "https://danwang.co/2020-letter/",
    year: 2020,
    author: "Dan Wang",
    title: "2020 Letter",
    preview:
      "Centralized campaigns of inspiration; Proust; rejecting complacency and decadence; the pandemic in Beijing; brown sauce; riding a bike; rejuvenation.",
    wordCount: 11660,
  },
  {
    id: "karpathy-2025",
    url: "https://karpathy.bearblog.dev/year-in-review-2025/",
    year: 2025,
    author: "Andrej Karpathy",
    title: "Year in Review 2025",
    preview: "2025 Year in Review of LLM paradigm changes",
    wordCount: 1908,
  },
  {
    id: "simonwillison-2025",
    url: "https://simonwillison.net/2025/Dec/31/the-year-in-llms/",
    year: 2025,
    author: "Simon Willison",
    title: "The Year in LLMs",
    preview:
      "This is the third in my annual series reviewing everything that happened in the LLM space over the past 12 months. For previous years see Stuff we figured out about …",
    wordCount: 8224,
  },
  {
    id: "simonwillison-2024",
    url: "https://simonwillison.net/2024/Dec/31/llms-in-2024/",
    year: 2024,
    author: "Simon Willison",
    title: "LLMs in 2024",
    preview:
      "A lot has happened in the world of Large Language Models over the course of 2024. Here’s a review of things we figured out about the field in the past …",
    wordCount: 7601,
  },
  {
    id: "simonwillison-2023",
    url: "https://simonwillison.net/2023/Dec/31/ai-in-2023/",
    year: 2023,
    author: "Simon Willison",
    title: "AI in 2023",
    preview:
      "2023 was the breakthrough year for Large Language Models (LLMs). I think it’s OK to call these AI—they’re the latest and (currently) most interesting development in the academic field of …",
    wordCount: 3511,
  },
  {
    id: "zvi-mowshowitz-2025",
    url: "https://thezvi.substack.com/p/2025-year-in-review",
    year: 2025,
    author: "Zvi Mowshowitz",
    title: "2025 Year in Review",
    preview: "It’s that time.",
    wordCount: 3978,
  },
  {
    id: "nate-silver-2025",
    url: "https://www.natesilver.net/p/the-silver-bulletin-year-in-review",
    year: 2025,
    author: "Nate Silver",
    title: "The Silver Bulletin Year in Review",
    preview:
      "My favorite posts of 2025, some notes on the business, and a thank you to our readers.",
    wordCount: 3949,
  },
  {
    id: "jimzub-2025",
    url: "https://jimzub.substack.com/p/zubby-newsletter-140-year-in-review",
    year: 2025,
    author: "Jim Zub",
    title: "Zubby Newsletter #140: Year In Review",
    preview:
      "For the past 15 years I’ve put together a ‘Year In Review‘ post on my website as a way to summarize my thoughts and feelings on the year that was.",
    wordCount: 1024,
  },
  {
    id: "michael-mcfaul-2025",
    url: "https://michaelmcfaul.substack.com/p/mcfauls-world-2025-year-in-review",
    year: 2025,
    author: "Michael McFaul",
    title: "McFaul’s World — 2025 Year in Review",
    preview: "Looking back on a turbulent year.",
    wordCount: 1427,
  },
  {
    id: "nathan-lambert-2025",
    url: "https://substack.com/home/post/p-181486818?source=queue",
    year: 2025,
    author: "Nathan Lambert",
    title: "2025 Interconnects year in review",
    preview: "Three years writing every week about AI.",
    wordCount: 2049,
  },
  {
    id: "noah-smith-2025",
    url: "https://www.noahpinion.blog/p/noahpinions-2025-year-in-review?triedRedirect=true",
    year: 2025,
    author: "Noah Smith",
    title: "Noahpinion's 2025 Year in Review",
    preview: "Year Five of the Noahpinion Substack.",
    wordCount: 3164,
  },
  {
    id: "james-stanier-2024",
    url: "https://theengineeringmanager.substack.com/p/2024-the-year-in-review",
    year: 2024,
    author: "James Stanier",
    title: "2024: the year in review",
    preview: "Efficiency, optimism, and not getting left behind.",
    wordCount: 2648,
  },
  {
    id: "matthew-long-2024",
    url: "https://matthewmlong.substack.com/p/2024-year-in-review",
    year: 2024,
    author: "Matthew Long",
    title: "2024 Year-in-Review",
    preview: "In which I share my reading journey for 2024",
    wordCount: 679,
  },
  {
    id: "connor-swenson-2024",
    url: "https://onepercentwisdom.substack.com/p/2024-annual-review",
    year: 2024,
    author: "Connor Swenson",
    title: "2024 Annual Review",
    preview: "The Year of Kaia",
    wordCount: 3941,
  },
  {
    id: "phillips-p-obrien-2024",
    url: "https://phillipspobrien.substack.com/p/2024-year-in-review-part-1",
    year: 2024,
    author: "Phillips P. OBrien",
    title: "2024 Year in Review: Part 1",
    preview: "How Historians Might Write the Russo-Ukraine War.",
    wordCount: 238,
  },
  {
    id: "jarrett-fuller-2024",
    url: "https://jarrettfuller.substack.com/p/38-a-2024-year-in-review",
    year: 2024,
    author: "Jarrett Fuller",
    title: "38. A 2024 Year in Review",
    preview: "Happy new year!",
    wordCount: 1523,
  },
  {
    id: "mischa-willett-2024",
    url: "https://mischawillett.substack.com/p/year-in-review-2024",
    year: 2024,
    author: "Mischa Willett",
    title: "Year in Review 2024",
    preview: "'I will build a boat in the desert place'",
    wordCount: 866,
  },
  {
    id: "cl-kao-2023",
    url: "https://clkao.substack.com/p/2023-year-in-review",
    year: 2023,
    author: "CL Kao",
    title: "2023 Year In Review",
    preview: "The Geekway, and may we all focus on what is meaningful",
    wordCount: 321,
  },
  {
    id: "michael-mcfaul-2023",
    url: "https://michaelmcfaul.substack.com/p/mcfauls-world-2023-year-in-review",
    year: 2023,
    author: "Michael McFaul",
    title: "McFaul’s World – 2023 Year in Review",
    preview: "Hoping for a more peaceful 2024!",
    wordCount: 1772,
  },
  {
    id: "daniel-bashir-2023",
    url: "https://thegradientpub.substack.com/p/a-year-in-review-2023",
    year: 2023,
    author: "daniel bashir",
    title: "A Year in Review: 2023",
    preview: "A thank you, and a reminder about our mission",
    wordCount: 1308,
  },
  {
    id: "nathan-lambert-2024",
    url: "https://www.interconnects.ai/p/2024-interconnects-year-in-review",
    year: 2024,
    author: "Nathan Lambert",
    title: "2024 Interconnects year in review",
    preview: "Two years writing every week on AI.",
    wordCount: 1813,
  },
  {
    id: "nathan-lambert-2023",
    url: "https://www.interconnects.ai/p/2023-review",
    year: 2023,
    author: "Nathan Lambert",
    title: "Interconnects year in review: 2023",
    preview:
      "The core themes of ML and the blog this year. What changes in 2024.",
    wordCount: 2486,
  },
  {
    id: "nathan-lambert-2020",
    url: "https://www.interconnects.ai/p/2020",
    year: 2020,
    author: "Nathan Lambert",
    title: "Democratizing Automation 2020: (half) year in review",
    preview:
      "How I ended up with 26 posts in my first half year of weekly writing. What we learned and where we are going.",
    wordCount: 1228,
  },
  {
    id: "janelle-teng-wade-2025",
    url: "https://nextbigteng.substack.com/p/2025-year-in-review-ai-bubble-or-breakthrough",
    year: 2025,
    author: "Janelle Teng Wade",
    title: "2025 Year-In-Review: AI Bubble or Breakthrough?",
    preview:
      "From power-law breakouts to bubble concerns, my final post of 2025 takes a retrospective look at the most consequential AI debates of the year and examines what these signals may reveal for 2026.",
    wordCount: 1312,
  },
  {
    id: "janelle-teng-wade-2024",
    url: "https://nextbigteng.substack.com/p/saasy-predictions-for-2024",
    year: 2024,
    author: "Janelle Teng Wade",
    title: "SaaSy Predictions for 2024",
    preview:
      "In every last post of the year, I reflect on notable events from the past 12 months & offer predictions on the next big thing for the new year. Trigger warning for 2024: a lot more AI content ahead...",
    wordCount: 2153,
  },
  {
    id: "janelle-teng-wade-2023",
    url: "https://nextbigteng.substack.com/p/saasy-predictions-for-2023",
    year: 2023,
    author: "Janelle Teng Wade",
    title: "SaaSy Predictions for 2023",
    preview:
      "In this final post of 2022, I revisit notable events which have defined this tumultuous year for cloud companies and offer some predictions on what the next big thing in SaaS might look like in 2023.",
    wordCount: 1772,
  },
  {
    id: "connor-swenson-2023",
    url: "https://onepercentwisdom.substack.com/p/2023-in-review-ola-portugal",
    year: 2023,
    author: "Connor Swenson",
    title: "2023 In Review: Olá, Portugal!",
    preview: "My 2023 Personal Annual Review",
    wordCount: 2237,
  },
  {
    id: "connor-swenson-2021",
    url: "https://onepercentwisdom.substack.com/p/14103661_one-percent-wisdom-2021-annual-review-jan-13-2022",
    year: 2021,
    author: "Connor Swenson",
    title: "Annual Review 2021 | #68",
    preview: "One Percent Wisdom",
    wordCount: 413,
  },
  {
    id: "jordan-gonen-2025",
    url: "https://docs.google.com/document/d/1PfFa7kCBM7EzPntEulCeGbSWHKt_uYuJp4OuKtRW7n4/edit?tab=t.0",
    year: 2025,
    author: "Jordan Gonen",
    title: "2025 // JORDAN GONEN",
    preview:
      "some notes from 2025  “Remember the path.”  — Master Oogway, as he falls down a volcano.  * * *  “It is not bad. But also not good.”     “Hmm…okay…but do you think it meets your quality standard?”   “No. Still una...",
    wordCount: 2349,
  },
  {
    id: "jordan-gonen-2024",
    url: "https://docs.google.com/document/d/1V-r87yBT5yphoxz7owCRwYugqczzQNeSBdqJ8K75rVw/edit?tab=t.0",
    year: 2024,
    author: "Jordan Gonen",
    title: "2024 // jordan gonen",
    preview:
      "Them: “why?!!”  me, in 2024: “why _not_?”     2024 Started the year driving a rickshaw across Sri Lanka with Noah, Ben, Manny, and Jacob. It went about how you would expect.    Then I spent a day and night in Kuala Lum...",
    wordCount: 3528,
  },
  {
    id: "jordan-gonen-2023",
    url: "https://docs.google.com/document/d/1lbRXme-ZV1txPPaykqXlVIOu5sDZeXjUEU51T61JZc0/edit?tab=t.0#heading=h.a4fdlwr9tsxo",
    year: 2023,
    author: "Jordan Gonen",
    title: "2023 // Jordan Gonen",
    preview:
      "We were all very alive three year olds—full of curiosity, authenticity, and energy.  		    me Attempting to return to this youthful spirit—this quality without a name—has been my year.   I wrote and su...",
    wordCount: 1299,
  },
  {
    id: "jordan-gonen-2022",
    url: "https://docs.google.com/document/d/1v7e-ZrkyF4pW21sQHpERaFA34digSOy4CM2B7BKmP2Y/edit?tab=t.0#heading=h.kqyjqaax421q",
    year: 2022,
    author: "Jordan Gonen",
    title: "2022 // Jordan Gonen",
    preview:
      "JG from the future: disclaimer - I now disagree with many of the takeaways from this essay.   --  Life is short. Too short for bullshit. Bullshit is a provocative term—think pointless meetings and boring content...",
    wordCount: 2289,
  },
  {
    id: "jordan-gonen-2021",
    url: "https://docs.google.com/document/d/1PdNbpPw4YG-dJtkaYMQ3szjDhBVSZyvYk8hUaXgjolE/edit?tab=t.0",
    year: 2021,
    author: "Jordan Gonen",
    title: "2021 // Jordan Gonen",
    preview:
      "Thanks for all the help :)   2021:  Found an editor to critique all of my writing.  Got the iPhone mini (for some reason, this upsets people).  Ran the San Francisco marathon.  Worked on Compound.  Spent time in SF, LA, PHX, NYC, and the DR.  Experienced...",
    wordCount: 841,
  },
  {
    id: "jordan-gonen-2020",
    url: "https://docs.google.com/document/d/1UNaBsft38GgNEsv4Obtw4oo4FMpdRFzVtadyDPMyXx4/edit?tab=t.0",
    year: 2020,
    author: "Jordan Gonen",
    title: "2020 // Jordan Gonen",
    preview:
      "Writing this reflection feels different, largely because 2020 was a very different type of year. Different due to macro events (e.g., global pandemic), yes, but also personal reasons.   I’m very very lucky. I’m healthy. My friends ...",
    wordCount: 1134,
  },
  {
    id: "jordan-gonen-2019",
    url: "https://docs.google.com/document/d/1oORERl-T1t_-N-oyoztpProow8cg5AW-uYxSbMh9rdA/edit?tab=t.0",
    year: 2019,
    author: "Jordan Gonen",
    title: "2019 // Jordan Gonen",
    preview:
      "🛸 Every December, I publish some sort of “Year in Review” style essay.  I do this mainly for myself: to exercise my brain, capture memories, and say thank you.   Reviewing previous editions (2016, 2017, 2018), I reflect upon my diversified portfolio of disjoint life experiences and know that thi...",
    wordCount: 2222,
  },
  {
    id: "jordan-gonen-2018",
    url: "https://gonen.blog/2018-my-year-in-review/",
    year: 2018,
    author: "Jordan Gonen",
    title: "2018: My Year in Review – Jordan Gonen",
    preview:
      "I cannot believe that this year is coming to an end. 2018 has been a whirlwind of adventure — a period of unpredictable chaos and extreme learning.",
    wordCount: 2593,
  },
  {
    id: "jordan-gonen-2017",
    url: "https://gonen.blog/2017-my-year-in-review/",
    year: 2017,
    author: "Jordan Gonen",
    title: "2017: My Year in Review – Jordan Gonen",
    preview:
      "As we close out 2017, I, yet again, type in a state of reflection.",
    wordCount: 2684,
  },
  {
    id: "dan-wang-2019",
    url: "https://danwang.co/2019-letter/",
    year: 2019,
    author: "Dan Wang",
    title: "2019 letter | Dan Wang",
    preview:
      "Retail sanity and wholesale madness; China's technology position; elephantasies; the Nazi war economy; Philip K. Dick; the golden mole; interchangeability.",
    wordCount: 9780,
  },
  {
    id: "dan-wang-2017",
    url: "https://danwang.co/2017-letter/",
    year: 2017,
    author: "Dan Wang",
    title: "2017 letter | Dan Wang",
    preview:
      "Some of the things I learned in 2017; Buddenbrooks should be set in Hangzhou; the novelty of traveling in China; Deutsches Requiem in the Upper West Side.",
    wordCount: 3627,
  },
  {
    id: "dan-wang-2018",
    url: "https://danwang.co/2018-letter/",
    year: 2018,
    author: "Dan Wang",
    title: "2018 letter | Dan Wang",
    preview:
      "Exuberant cultural élan; the optimisms of Kennedy and Khrushchev; Exact Thinking in Demented Times; the golf of tech; Lady Macbeth; Hangzhou and Chongqing.",
    wordCount: 6492,
  },
  {
    id: "psmith-2025",
    url: "https://www.thepsmiths.com/p/2025-the-year-in-reviews",
    year: 2025,
    author: "Jane Psmith and John Psmith",
    title: "2025: The Year in Review(s)",
    preview:
      "Jane: Well, we’ve done it again: despite the many forces militating against us (our children, your job, an exciting variety of upper respiratory infections, that one time my library e-book expired halfway through writing my review and I had to pay for an actual copy), we’ve kept this wacky joint project going another year.",
    wordCount: 3583,
  },
  {
    id: "henry-oliver-2025",
    url: "https://www.commonreader.co.uk/p/year-in-review-2025",
    year: 2025,
    author: "Henry Oliver",
    title: "Year in review, 2025",
    preview: "Another good year",
    wordCount: 636,
  },
  {
    id: "ryanckulp-2025",
    url: "https://www.ryanckulp.com/2025-in-review/",
    year: 2025,
    author: "ryanckulp",
    title: "2025 in review",
    preview:
      "at the end of 2024 i announced a year long speedrun. here’s what happened: now for the longer version. family my wife and i welcomedRead More",
    wordCount: 976,
  },
  {
    id: "tom-macwright-2025",
    url: "https://macwright.com/2025/12/07/year-in-review.html",
    year: 2025,
    author: "Tom MacWright",
    title: "2025 Year in Review",
    preview: "JavaScript, math, maps, etc",
    wordCount: 1671,
  },
  {
    id: "marshallhaas-2021",
    url: "https://www.marshallhaas.com/post/2021-year-in-review-the-year-i-delegated-everything",
    year: 2021,
    author: "Marshall Haas",
    title: "2021 Year In Review –  The Year I Delegated Everything",
    preview:
      "Aug 08, 2024  –  This year I delegated almost everything across my 3 companies. I ordered my dream car, we broke ground on our cabin, and life was pretty great as a Dad. It was a jam packed year.",
    wordCount: 2666,
  },
  {
    id: "marshallhaas-2018",
    url: "https://www.marshallhaas.com/post/2018-year-in-review",
    year: 2018,
    author: "Marshall Haas",
    title: "2018 Year In Review – My Most Profitable Year",
    preview:
      "Jan 05, 2022  –  I’ve now been an entrepreneur for 10 years. As with any stage of entrepreneurship, there are ups and downs every day. This year was no exception. That said, many things came together this year that I put in motion long ago. All in, it was the most profitable year of my career.",
    wordCount: 2970,
  },
  {
    id: "marshallhaas-2015",
    url: "https://www.marshallhaas.com/post/2015-business-year-in-review-our-best-year-yet",
    year: 2015,
    author: "Marshall Haas",
    title: "2015 Business Year In Review – Our Best Year Yet",
    preview:
      "May 03, 2021  –  Wow. This year was a rollercoaster. We’ve now been in business for 2 years. As CEO of Need/Want, part of my job is to constantly take a birds eye view of our business. It helps me steer the ship. Let's take a look back at where we went this year.",
    wordCount: 3194,
  },
  {
    id: "stay-saasy-2024",
    url: "https://blog.staysaasy.com/p/2024-a-saasy-year-in-review",
    year: 2024,
    author: "Stay SaaSy",
    title: "2024: A SaaSy Year In Review",
    preview: "Next year is bound to be odd.",
    wordCount: 515,
  },
  {
    id: "psmith-2024",
    url: "https://www.thepsmiths.com/p/2024-the-year-in-reviews",
    year: 2024,
    author: "Jane Psmith and John Psmith",
    title: "2024: The Year in Review(s)",
    preview: "Jane: Well, it’s been another year chez Psmiths.",
    wordCount: 3400,
  },
  {
    id: "psmith-2023",
    url: "https://www.thepsmiths.com/p/2023-the-year-in-reviews",
    year: 2023,
    author: "Jane Psmith and John Psmith",
    title: "2023: The Year in Review(s)",
    preview:
      "Jane: So, it’s been almost year since I said, “hey, we should start a book review Substack” and I think it’s turned out pretty well.",
    wordCount: 1882,
  },
  {
    id: "henry-oliver-2022",
    url: "https://www.commonreader.co.uk/p/year-in-review",
    year: 2022,
    author: "Henry Oliver",
    title: "Year in Review",
    preview: "A man ought to read just as inclination leads him",
    wordCount: 718,
  },
  {
    id: "henry-oliver-2024",
    url: "https://www.commonreader.co.uk/p/year-in-review-2024",
    year: 2024,
    author: "Henry Oliver",
    title: "Year in review, 2024",
    preview: "Another good year",
    wordCount: 567,
  },
  {
    id: "henry-oliver-2023",
    url: "https://www.commonreader.co.uk/p/year-in-review-2023",
    year: 2023,
    author: "Henry Oliver",
    title: "Year in Review, 2023",
    preview: "Popular essays, finishing my book, Victorian literature",
    wordCount: 640,
  },
  {
    id: "ryanckulp-2022",
    url: "https://www.ryanckulp.com/2022-in-review/",
    year: 2022,
    author: "ryanckulp",
    title: "2022 in Review",
    preview: "It's not about what I did in 2022, but what 2022 did to me.",
    wordCount: 759,
  },
  {
    id: "ryanckulp-2013",
    url: "https://www.ryanckulp.com/2013-in-review/",
    year: 2013,
    author: "ryanckulp",
    title: "2013 in Review",
    preview: "2013 was insane. Here's why.",
    wordCount: 153,
  },
  {
    id: "tom-macwright-2023",
    url: "https://macwright.com/2023/12/28/year-in-review",
    year: 2023,
    author: "Tom MacWright",
    title: "Year in Review",
    preview:
      "Richard Rorty, New York City, watching The Favorite, running, and reading.",
    wordCount: 1328,
  },
  {
    id: "tom-macwright-2012",
    url: "https://macwright.com/2012/07/04/a-year",
    year: 2012,
    author: "Tom MacWright",
    title: "A Year",
    preview: "A celebration of the first year of this blog.",
    wordCount: 335,
  },
  {
    id: "tom-macwright-2017",
    url: "https://macwright.com/2017/12/22/year-in-review",
    year: 2017,
    author: "Tom MacWright",
    title: "Year in review",
    preview: "or, convincing myself that I didn't do nothing",
    wordCount: 379,
  },
  {
    id: "stay-saasy-2023",
    url: "https://blog.staysaasy.com/p/2023-a-saasy-year-in-review",
    year: 2023,
    author: "Stay SaaSy",
    title: "2023: A SaaSy Year In Review",
    preview: "Reflections on a very SaaSy year",
    wordCount: 1561,
  },
  {
    id: "stay-saasy-2021",
    url: "https://blog.staysaasy.com/p/one-yearhtml",
    year: 2021,
    author: "Stay SaaSy",
    title: "A Year Of SaaSiness",
    preview:
      "Today - April 6th - is our 1 year anniversary of posting on our blog, staysaasy.com. In almost every way, the outcomes have surpassed our expectations. Here are some reflections on the experience so far.",
    wordCount: 530,
  },
  {
    id: "justinjackson-2020",
    url: "https://justinjackson.ca/2020-review",
    year: 2020,
    author: "Justin Jackson",
    title: "2020 year in review",
    preview:
      "For those following my story: 2020 was a breakout year for me. After years of trying, I finally feel like I have a life with margin and a business that can sustain it.",
    wordCount: 1409,
  },
  {
    id: "trungphan-2025",
    url: "https://www.readtrung.com/p/11-best-things-of-2025",
    year: 2025,
    author: "Trung Phan",
    title: "11 Best Things of 2025",
    preview:
      "My favourite book, film, podcast, live event, song, meme, purchase and more for the year.",
    wordCount: 7673,
  },
  {
    id: "trungphan-2024",
    url: "https://www.readtrung.com/p/11-best-things-of-2024",
    year: 2024,
    author: "Trung Phan",
    title: "11 Best Things of 2024",
    preview:
      "My favourite book, film, podcast, quote, meme, purchase and more for the year.",
    wordCount: 5900,
  },
  {
    id: "trungphan-2023",
    url: "https://www.readtrung.com/p/9-best-things-of-2023",
    year: 2023,
    author: "Trung Phan",
    title: "9 Best Things of 2023",
    preview:
      "My favourite book, film, podcast, meme, investment and more for the year.",
    wordCount: 2979,
  },
  {
    id: "sasha-chapin-2021",
    url: "https://sashachapin.substack.com/p/2021-year-in-review",
    year: 2021,
    author: "Sasha Chapin",
    title: "2021 Year in Review",
    preview: "It was a very good year",
    wordCount: 1008,
  },
  {
    id: "sasha-chapin-2025",
    url: "https://sashachapin.substack.com/p/year-in-review-2025",
    year: 2025,
    author: "Sasha Chapin",
    title: "Year in review 2025",
    preview: "a very good year",
    wordCount: 81,
  },
  {
    id: "gergely-orosz-2022",
    url: "https://newsletter.pragmaticengineer.com/p/the-pragmatic-engineer-in-2022",
    year: 2022,
    author: "Gergely Orosz",
    title: "The Pragmatic Engineer in 2022",
    preview:
      "The articles you enjoyed most this year, my personal favorites, and a recap of a busy year in tech news.",
    wordCount: 2371,
  },
  {
    id: "gergely-orosz-2025",
    url: "https://newsletter.pragmaticengineer.com/p/the-pragmatic-engineer-in-2025",
    year: 2025,
    author: "Gergely Orosz",
    title: "The Pragmatic Engineer in 2025",
    preview:
      "The most-read articles of the year, plus some personal favorites, and a look back at a busy year in tech",
    wordCount: 2071,
  },
  {
    id: "gergely-orosz-2024",
    url: "https://newsletter.pragmaticengineer.com/p/wrapped-the-pragmatic-engineer-in",
    year: 2024,
    author: "Gergely Orosz",
    title: "Wrapped: The Pragmatic Engineer in 2024",
    preview:
      "The year’s most-read articles, some personal favorites, and a look back at a busy year in tech",
    wordCount: 2704,
  },
  {
    id: "gergely-orosz-2023",
    url: "https://newsletter.pragmaticengineer.com/p/the-pragmatic-engineer-in-2023",
    year: 2023,
    author: "Gergely Orosz",
    title: "The Pragmatic Engineer in 2023",
    preview:
      "The articles you enjoyed most this year, my personal favorites, and a recap of an unusually turubulent year in tech.",
    wordCount: 3298,
  },
  {
    id: "gergely-orosz-2021",
    url: "https://newsletter.pragmaticengineer.com/p/2021-review",
    year: 2021,
    author: "Gergely Orosz",
    title: "2021 in Review",
    preview: "How the newsletter grew, most-read issues, and the numbers.",
    wordCount: 1749,
  },
  {
    id: "will-larson-2025",
    url: "https://lethain.com/2025-in-review/",
    year: 2025,
    author: "Will Larson",
    title: "2025 in review.",
    preview:
      "Yet another edition of my annual recap! This year brought my son to kindergarten, me to forty and to a new job at Imprint, my fourth book to bookstores, and a lot more time in the weeds of developing software.",
    wordCount: 1065,
  },
  {
    id: "will-larson-2024",
    url: "https://lethain.com/2024-in-review/",
    year: 2024,
    author: "Will Larson",
    title: "2024 in review.",
    preview:
      "A lot happened for me this year. I continued learning the details of fund accounting at Carta, which is likely the most complex product domain I’ve worked in. My third book was published, and I did a small speaking tour to support it.",
    wordCount: 2162,
  },
  {
    id: "will-larson-2023",
    url: "https://lethain.com/2023-in-review/",
    year: 2023,
    author: "Will Larson",
    title: "2023 in review.",
    preview:
      "This was an eventful year. My son went to preschool, I joined Carta, left Calm, and wrote my third book. It was also a logistically intensive year, with our toddler heading to preschool, more work travel, and a bunch of other little bits and pieces. Here is my year in review summary. I love to read other folks year-in writeups – if you write one, please send it my way!",
    wordCount: 1843,
  },
  {
    id: "will-larson-2022",
    url: "https://lethain.com/2022-in-review/",
    year: 2022,
    author: "Will Larson",
    title: "2022 in review.",
    preview:
      "Previously: 2021, 2020, 2019, 2018, 2017 After the past two years, it’s odd to write an annual reflection where my first thoughts are happy rather than bleak. The truth is that there is a lot of bleak out there right now–just look at the layoffs and the funding environment–but while last year was an unusual and challenging one for me, this one was relatively quiet for me and my family. That said, even a quiet year is worth a bit of introspection, so here is my annual note.",
    wordCount: 2560,
  },
  {
    id: "will-larson-2021",
    url: "https://lethain.com/2021-in-review/",
    year: 2021,
    author: "Will Larson",
    title: "2021 in review.",
    preview:
      "It’s always tricky to figure out the right tone for an annual wrapup post. This has been one of the best years of my life. Our son is now a walking toddler. I released my second book, Staff Engineer, and it’s done well. I learned a tremendous amount supporting the engineering and data science teams at Calm. My weekly basketball game resumed after a 15 month hiatus. A secondary transaction at a previous company meaningfully changed my life financially.",
    wordCount: 1605,
  },
  {
    id: "will-larson-2020",
    url: "https://lethain.com/2020-in-review/",
    year: 2020,
    author: "Will Larson",
    title: "2020 in review.",
    preview:
      "I’m returning to work from parental leave this week, and felt like taking the moment to to write my 2020 review now rather than waiting for the end of the month. It’s been a wild year, with a lot of very good things personally, and a lot of very bad things nationally and globally.",
    wordCount: 2306,
  },
  {
    id: "will-larson-2019",
    url: "https://lethain.com/2019-in-review/",
    year: 2019,
    author: "Will Larson",
    title: "2019 in review.",
    preview:
      "This has been a really special year for me personally, enough so that even though I won’t get into full detail about the two things (one professional, one personal) I’m most excited about (more in a month or two), writing a year-in-review still fills me with gratitude.",
    wordCount: 2480,
  },
  {
    id: "will-larson-2018",
    url: "https://lethain.com/2018-in-review/",
    year: 2018,
    author: "Will Larson",
    title: "2018 in review.",
    preview:
      "By far the most rewarding thing I did this year was marrying a wonderful person. My sister also married, and my sister-in-law is getting married in the spring of next year. In such a sea of marriages, it feels a bit trite to write a year review on my writing hobby, but what’s a hobby good for if not enabling trite behavior?",
    wordCount: 1420,
  },
  {
    id: "will-larson-2017",
    url: "https://lethain.com/things-learned-in-2017/",
    year: 2017,
    author: "Will Larson",
    title: "Engineering management stuff I learned in 2017.",
    preview:
      "I’ve been working with Stripe’s infrastructure engineering team for 2017, getting to work an increasingly interesting set of problems, at an increasingly large scale, and with an increasingly talented group of folks. These are some of the things I got to learn over the past year.",
    wordCount: 1028,
  },
  {
    id: "stratechery-2025",
    url: "https://stratechery.com/2025/the-2025-stratechery-year-in-review/",
    year: 2025,
    author: "Ben Thompson",
    title: "The 2025 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2025.",
    wordCount: 1897,
  },
  {
    id: "stratechery-2024",
    url: "https://stratechery.com/2024/the-2024-stratechery-year-in-review/",
    year: 2024,
    author: "Ben Thompson",
    title: "The 2024 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2024.",
    wordCount: 1909,
  },
  {
    id: "stratechery-2023",
    url: "https://stratechery.com/2023/the-2023-stratechery-year-in-review/",
    year: 2023,
    author: "Ben Thompson",
    title: "The 2023 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2023.",
    wordCount: 2049,
  },
  {
    id: "stratechery-2022",
    url: "https://stratechery.com/2022/the-2022-stratechery-year-in-review/",
    year: 2022,
    author: "Ben Thompson",
    title: "The 2022 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2022.",
    wordCount: 3030,
  },
  {
    id: "stratechery-2021",
    url: "https://stratechery.com/2021/the-2021-stratechery-year-in-review/",
    year: 2021,
    author: "Ben Thompson",
    title: "The 2021 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2021.",
    wordCount: 2811,
  },
  {
    id: "stratechery-2020",
    url: "https://stratechery.com/2020/the-2020-stratechery-year-in-review/",
    year: 2020,
    author: "Ben Thompson",
    title: "The 2020 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2020.",
    wordCount: 2564,
  },
  {
    id: "stratechery-2019",
    url: "https://stratechery.com/2019/the-2019-stratechery-year-in-review/",
    year: 2019,
    author: "Ben Thompson",
    title: "The 2019 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2019.",
    wordCount: 2507,
  },
  {
    id: "stratechery-2018",
    url: "https://stratechery.com/2018/the-2018-stratechery-year-in-review/",
    year: 2018,
    author: "Ben Thompson",
    title: "The 2018 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2018.",
    wordCount: 2064,
  },
  {
    id: "stratechery-2017",
    url: "https://stratechery.com/2017/the-2017-stratechery-year-in-review/",
    year: 2017,
    author: "Ben Thompson",
    title: "The 2017 Stratechery Year in Review",
    preview:
      "The most popular and most important posts on Stratechery in 2017.",
    wordCount: 1629,
  },
  {
    id: "stratechery-2016",
    url: "https://stratechery.com/2016/the-2016-stratechery-year-in-review/",
    year: 2016,
    author: "Ben Thompson",
    title: "The 2016 Stratechery Year in Review",
    preview: "The top posts on Stratechery in 2016",
    wordCount: 1522,
  },
  {
    id: "stratechery-2015",
    url: "https://stratechery.com/2015/the-stratechery-2015-year-in-review/",
    year: 2015,
    author: "Ben Thompson",
    title: "The 2015 Stratechery Year in Review",
    preview:
      "The top five most read posts, big ideas, company-specific posts, posts about media, and Daily Updates of 2015.",
    wordCount: 1436,
  },
  {
    id: "stratechery-2014",
    url: "https://stratechery.com/2014/stratechery-2014-year-review/",
    year: 2014,
    author: "Ben Thompson",
    title: "The 2014 Stratechery Year in Review",
    preview:
      "2014 was Stratechery’s second year, and what a momentous one it was! In April Stratechery became my full-time job, and although I made some quick changes to the model, it’s been a big s…",
    wordCount: 1213,
  },
  {
    id: "stratechery-2013",
    url: "https://stratechery.com/2013/stratechery-2013-year-review/",
    year: 2013,
    author: "Ben Thompson",
    title: "The 2013 Stratechery Year In Review",
    preview:
      "Stratechery launched on March 25, 2013 with the post Welcome to Stratechery. While I had somewhat prepopulated the blog with old content (including a piece on the original iPad and a research paper…",
    wordCount: 938,
  },
  {
    id: "justin-jackson-2025",
    url: "https://justinjackson.ca/2025-review",
    year: 2025,
    author: "Justin Jackson",
    title: "2025 year in review",
    preview:
      "For the last twelve years, I've been writing a year-in-review post. Here's what happened this past year in my journey.",
    wordCount: 1919,
  },
  {
    id: "mijustin-2024",
    url: "https://justinjackson.ca/2024-review",
    year: 2024,
    author: "Justin Jackson",
    title: "2024 year in review",
    preview:
      "For the last eleven years, I've been writing a year-in-review post. Here's what happened this past year in my journey.",
    wordCount: 2897,
  },
  {
    id: "justin-jackson-2023",
    url: "https://justinjackson.ca/2023-review",
    year: 2023,
    author: "Justin Jackson",
    title: "2023 year in review",
    preview:
      "For the last ten years, I've been writing a year-in-review post. Here's what happened this past year in my bootstrapping journey.",
    wordCount: 2853,
  },
  {
    id: "justin-jackson-2022",
    url: "https://justinjackson.ca/2022-review",
    year: 2022,
    author: "Justin Jackson",
    title: "2022 year in review",
    preview:
      "Every year, I write a year-in-review blog post. Here are my business/bootstrapping highlights, plus a few personal experiences.",
    wordCount: 2277,
  },
  {
    id: "justin-jackson-2018",
    url: "https://justinjackson.ca/2018-review",
    year: 2018,
    author: "Justin Jackson",
    title: "2018 year in review",
    preview:
      "My aim here was to paint the most honest picture possible. Too often, people's annual reviews only trumpet the positive highlights.",
    wordCount: 1635,
  },
  {
    id: "justin-jackson-2017",
    url: "https://justinjackson.ca/2017-review",
    year: 2017,
    author: "Justin Jackson",
    title: "2017 year in review",
    preview:
      "What did I learn? What was hard? What am I thankful for? What are my plans for 2018? (Spoiler: I'm starting a SaaS and doubling down on Tiny Wins). I'm grateful for 2017, even though personally it was my most difficult.",
    wordCount: 1686,
  },
  {
    id: "justin-jackson-2015",
    url: "https://justinjackson.ca/2015-in-review",
    year: 2015,
    author: "Justin Jackson",
    title: "Make stuff and be happy (2015 year in review)",
    preview:
      "When I make stuff, I'm happy. When I don't make stuff, I'm not as happy. This theme keeps getting reinforced, year after year.",
    wordCount: 1541,
  },
  {
    id: "justin-jackson-2019",
    url: "https://justinjackson.ca/2019-review",
    year: 2019,
    author: "Justin Jackson",
    title: "2019 year in review",
    preview:
      "Last year, around this time, I wasn't feeling like a winner. But in 2019, a lot changed.",
    wordCount: 1099,
  },
  {
    id: "justin-jackson-2016",
    url: "https://justinjackson.ca/2016-review",
    year: 2016,
    author: "Justin Jackson",
    title: "Going independent (2016 year in review)",
    preview:
      "We were 26 years old. We had two young kids at home. And we'd just closed our retail business.",
    wordCount: 1706,
  },
  {
    id: "justin-jackson-2014",
    url: "https://justinjackson.ca/2014-a-year-of-making-stuff",
    year: 2014,
    author: "Justin Jackson",
    title: "2014: a year of making stuff",
    preview:
      "Before making my goals for 2015, I wanted to review 2014. Sometimes we lose sight of what we've accomplished the previous year. Here's the framework I'm using to review myself personally - you can get the worksheet here.",
    wordCount: 1015,
  },
  {
    id: "other-internet-2022",
    url: "https://otherinternet.substack.com/p/other-internet-2022-year-in-review",
    year: 2022,
    author: "Other Internet",
    title: "Other Internet 2022: Year in Review",
    preview: "Dear friends, collaborators, and mentors:",
    wordCount: 1403,
  },
  {
    id: "nathan-baschez-2025",
    url: "https://buttondown.com/lex/archive/lex-annual-letter-why-dont-more-writers-use-ai/",
    year: 2025,
    author: "Nathan Baschez",
    title: "Lex Annual Letter: Why don’t more writers use AI?",
    preview:
      "Hi! Nathan here, founder of Lex. This week, a new tradition: an annual letter from me to you. By all measures, 2024 was an incredible year for Lex. We...",
    wordCount: 4116,
  },
  {
    id: "zhengdong-wang-2025",
    url: "https://zhengdongwang.com/2025/12/30/2025-letter.html",
    year: 2025,
    author: "Zhengdong Wang",
    title: "2025 letter",
    preview: "Zhengdong Wang’s personal website",
    wordCount: 11862,
  },
  {
    id: "zhengdong-wang-2024",
    url: "https://zhengdongwang.com/2024/12/29/2024-letter.html",
    year: 2024,
    author: "Zhengdong Wang",
    title: "2024 letter",
    preview: "Zhengdong Wang’s personal website",
    wordCount: 12365,
  },
  {
    id: "zhengdong-wang-2023",
    url: "https://zhengdongwang.com/2024/01/01/2023-letter.html",
    year: 2023,
    author: "Zhengdong Wang",
    title: "2023 letter",
    preview: "Zhengdong Wang’s personal website",
    wordCount: 13360,
  },
  {
    id: "zhengdong-wang-2022",
    url: "https://zhengdongwang.com/2022/12/28/2022-letter.html",
    year: 2022,
    author: "Zhengdong Wang",
    title: "2022 letter",
    preview: "Zhengdong Wang’s personal website",
    wordCount: 12175,
  },
  {
    id: "stripe-2021",
    url: "https://stripe.com/files/stripe-2021-update.pdf",
    year: 2021,
    author: "Patrick and John Collison",
    title: "Stripe 2021 Update",
    preview:
      "It’s an odd time to sit down and write an update on Stripe’s business and our industry. As the headlines switch abruptly from global pandemic to geopolitical tragedy, the machinations of the internet economy seem less pressing by comparison.",
    wordCount: 3027,
  },
  {
    id: "stripe-2022",
    url: "https://assets.stripeassets.com/fzn2n1nzq965/5Qj1NdQFtWO3rIE4WhAVl9/21202f8455f5a877444f91c1b48baf6e/stripe-2022-update.pdf",
    year: 2022,
    author: "Patrick and John Collison",
    title: "Stripe 2022 Update",
    preview:
      "Growing up, we only gradually came to realize that things around us weren’t just always there. Actual people, with concrete visions, working for a long time, made them happen. That hotel, that park, that railway. The world is a museum of passion projects.",
    wordCount: 4297,
  },
  {
    id: "stripe-2023",
    url: "https://assets.stripeassets.com/fzn2n1nzq965/1gMd12owbzJaSe4Y560OEJ/c5b932cbe8c0adc0ced520018584ff77/Stripe_2023_annual_letter.pdf",
    year: 2023,
    author: "Patrick and John Collison",
    title: "Stripe 2023 Annual Letter",
    preview:
      "Charlie Munger described a two-part rule that works wonders in business, science, and elsewhere: 1) take a simple idea and 2) take it very seriously.",
    wordCount: 5353,
  },
  {
    id: "stripe-2024",
    url: "https://assets.stripeassets.com/fzn2n1nzq965/2pt3yIHthraqR1KwXgr98U/b6301040587a62d5b6ef7b76c904032d/Stripe-annual-letter-2024.pdf",
    year: 2024,
    author: "Patrick and John Collison",
    title: "Stripe 2024 Annual Letter",
    wordCount: 4773,
  },
  {
    id: "jarred-kotzin-2024",
    url: "https://elevate.substack.com/p/2024-year-in-review",
    year: 2024,
    author: "Jarred Kotzin",
    title: "2024 year in review",
    preview: "2024 did not go according to plan.",
    wordCount: 2342,
  },
  {
    id: "jarred-kotzin-2023",
    url: "https://elevate.substack.com/p/2023-year-in-review",
    year: 2023,
    author: "Jarred Kotzin",
    title: "2023 year in review",
    preview: "walking the path",
    wordCount: 2214,
  },
  {
    id: "jarred-kotzin-2022",
    url: "https://elevate.substack.com/p/2022-year-in-review",
    year: 2022,
    author: "Jarred Kotzin",
    title: "2022 year in review",
    preview: "I can’t believe 2022 is over.",
    wordCount: 1965,
  },
  {
    id: "jarred-kotzin-2021",
    url: "https://elevate.substack.com/p/2021-year-in-review",
    year: 2021,
    author: "Jarred Kotzin",
    title: "2021 Year in Review",
    preview:
      "Sitting here writing this, I honestly can’t believe the year is over.",
    wordCount: 942,
  },
  {
    id: "julia-evans-2023",
    url: "https://jvns.ca/blog/2023/12/31/2023--year-in-review/",
    year: 2023,
    author: "Julia Evans",
    title: "2023: Year in review",
    preview: "2023: Year in review",
    wordCount: 1563,
  },
  {
    id: "julia-evans-2022",
    url: "https://jvns.ca/blog/2023/01/10/some-business-graphs-for-2022/",
    year: 2022,
    author: "Julia Evans",
    title: "Some business graphs for 2022",
    preview: "Some business graphs for 2022",
    wordCount: 1573,
  },
  {
    id: "julia-evans-2021",
    url: "https://jvns.ca/blog/2021/12/31/2021--year-in-review/",
    year: 2021,
    author: "Julia Evans",
    title: "2021: Year in review",
    preview: "2021: Year in review",
    wordCount: 1846,
  },
  {
    id: "julia-evans-2020",
    url: "https://jvns.ca/blog/2020/12/31/2020--year-in-review/",
    year: 2020,
    author: "Julia Evans",
    title: "2020: Year in review",
    preview: "2020: Year in review",
    wordCount: 1807,
  },
  {
    id: "julia-evans-2019",
    url: "https://jvns.ca/blog/2019-year-in-review/",
    year: 2019,
    author: "Julia Evans",
    title: "2019: Year in review",
    preview: "2019: Year in review",
    wordCount: 1258,
  },
  {
    id: "julia-evans-2018",
    url: "https://jvns.ca/blog/2018/12/23/2018--year-in-review/",
    year: 2018,
    author: "Julia Evans",
    title: "2018: Year in review",
    preview: "2018: Year in review",
    wordCount: 1457,
  },
  {
    id: "julia-evans-2017",
    url: "https://jvns.ca/blog/2017/12/31/2017--year-in-review/",
    year: 2017,
    author: "Julia Evans",
    title: "2017: Year in review",
    preview: "2017: Year in review",
    wordCount: 2009,
  },
  {
    id: "julia-evans-2016",
    url: "https://jvns.ca/blog/2016/12/21/2016--year-in-review/",
    year: 2016,
    author: "Julia Evans",
    title: "2016: Year in review",
    preview: "2016: Year in review",
    wordCount: 1315,
  },
  {
    id: "julia-evans-2015",
    url: "https://jvns.ca/blog/2015/12/26/2015-year-in-review/",
    year: 2015,
    author: "Julia Evans",
    title: "2015: Year in review",
    preview: "2015: Year in review",
    wordCount: 1436,
  },
  {
    id: "kyle-chayka-2023",
    url: "https://kylechayka.substack.com/p/my-year-in-review",
    year: 2023,
    author: "Kyle Chayka",
    title: "My year in review",
    preview: "Plus book tour dates!",
    wordCount: 1479,
  },
  {
    id: "permanent-equity-2025",
    url: "https://www.permanentequity.com/content/2025-annual-letter",
    year: 2025,
    author: "Brent Beshore",
    title:
      "Steady Progress and Self-Reflection — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "Contents Intro Fear of Man What CEOs Are and Aren’t AI: Helper, Not Replacer Fees and Performance Outside Board Members Selling for the Right Reasons 2025 Roundup Wrapping Up Health Update: Settling in for the Long Haul The Strange Math of Genero",
    wordCount: 18296,
  },
  {
    id: "permanent-equity-2024",
    url: "https://www.permanentequity.com/content/2024-annual-letter",
    year: 2024,
    author: "Brent Beshore",
    title:
      "Deep Roots, Hard Looks, and Change — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "“Progress is impossible without change, and those who cannot change their minds cannot change anything.” - George Bernard Shaw “Change your opinions, keep to your principles; change your leaves, keep intact your roots.” - Victor Hugo “Do not conform to the pattern of this world, but be trans",
    wordCount: 18656,
  },
  {
    id: "permanent-equity-2023",
    url: "https://www.permanentequity.com/content/2023-annual-letter",
    year: 2023,
    author: "Brent Beshore",
    title:
      "Awe, Health, and Fear: 2023 Annual Letter — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "Brent Beshore's annual letter on personal and professional learnings and observations throughout 2023 at the firm.",
    wordCount: 15862,
  },
  {
    id: "permanent-equity-2022",
    url: "https://www.permanentequity.com/content/15-years-in-the-trenches-of-smb-acquisitions-and-operations-2022-annual-letter",
    year: 2022,
    author: "Brent Beshore",
    title:
      "15 Years in the Trenches of SMB Acquisitions and Operations: 2022 Annual Letter — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "Our posture of patience, conservatism, emphasis on good decision-making, and long-term focus bore fruit in 2022 with a record year of investment, tremendous progress in building Permanent Equity for scale, and good financial results despite a tepid market and some tough situations. Reflections on 15",
    wordCount: 10764,
  },
  {
    id: "permanent-equity-2021",
    url: "https://www.permanentequity.com/content/the-score-takes-care-of-itself-2021-in-review",
    year: 2021,
    author: "Brent Beshore",
    title:
      "2021 Annual Letter: The Score Takes Care Of Itself — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "Read Brent Beshore's letter on Permanent Equity's 2021 performance and noteworthy lessons, including comments on operational culture, acquisitions closed, and achievements made by portfolio companies.",
    wordCount: 2864,
  },
  {
    id: "permanent-equity-2020",
    url: "https://www.permanentequity.com/content/lemons-and-mixology-2020-in-review",
    year: 2020,
    author: "Brent Beshore",
    title:
      "Lemons and Mixology: Our 2020 Annual Letter — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "We made it, despite viruses and murder hornets and political insanity. Rarely would I call mere survival a notable accomplishment, but hey, it was 2020. Personally, it has been a year of swings between intense anxiety, confusion, and hurry followed by peace, reflection, and deepening relationships.",
    wordCount: 9456,
  },
  {
    id: "permanent-equity-2019",
    url: "https://www.permanentequity.com/content/new-fund-new-partners-same-old-strategy-2019-in-review",
    year: 2019,
    author: "Brent Beshore",
    title:
      "New Fund, New Partners, Same Old Strategy: 2019 in Review — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "We raised Permanent Equity II, a $248M 27-year fund with a 10-year investment period; acquired three companies, which fully invested our first $50M fund (Permanent Equity I); launched the Scout Network; hired two managing directors and two portfolio company CEOs; and co-hosted one heck of a three-da",
    wordCount: 10468,
  },
  {
    id: "permanent-equity-2018",
    url: "https://www.permanentequity.com/content/serving-the-six-sided-teeter-totter-2018-in-review",
    year: 2018,
    author: "Brent Beshore",
    title:
      "Serving the Six-Sided Teeter Totter: 2018 in Review — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "Most of the year it felt like we were sitting in the middle of a big puzzle, during a particularly windy day, watching pieces plop down around us and scrambling to figure out how they all fit together. $50M fund raised. Wham. Two new portfolio companies. Bam. One sold. Whoosh. Compounding deal flow.",
    wordCount: 10952,
  },
  {
    id: "permanent-equity-2017",
    url: "https://www.permanentequity.com/content/going-pro-2017-in-review",
    year: 2017,
    author: "Brent Beshore",
    title:
      "Going Pro: 2017 In Review — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "What a year. We gave up our college eligibility and went pro, albeit in a late round of the draft, by raising a $50 million fund. It was our “big deal” of the year. More on that later.",
    wordCount: 11334,
  },
  {
    id: "permanent-equity-2016",
    url: "https://www.permanentequity.com/content/compounding-knowledge-and-returns-2016-year-in-review",
    year: 2016,
    author: "Brent Beshore",
    title:
      "Compounding Knowledge and Returns: 2016 Year in Review — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "While the world seemed to lose its collective mind for the better part of 2016, things at adventur.es hummed along nicely. 2016 was a year of fundamentals, stability, reinvestment, and organic growth. While we deployed capital into a handful of smaller transactions opportunistically, we didn’t close",
    wordCount: 3802,
  },
  {
    id: "permanent-equity-2015",
    url: "https://www.permanentequity.com/content/from-2000-to-3-2015-year-in-review",
    year: 2015,
    author: "Brent Beshore",
    title:
      "From 2000+ to 3: 2015 Year in Review — Permanent Equity: Investing in Companies that Care What Happens Next",
    preview:
      "People consistently ask us: “What makes Permanent Equity unique in the sea of potential investors?” We reviewed over 2000 qualified deals and deep-dived on 397, leading to 17 indications of interest (IOI) and 5 letters of intent (LOI). This afforded us a feedback loop of learning about how we are di",
    wordCount: 2438,
  },
  {
    id: "benjamin-parry-2024",
    url: "https://benparry.substack.com/p/2024-annual-letter",
    year: 2024,
    author: "Benjamin Parry",
    title: "2024 Annual Letter",
    preview: "Year in review and aims for 2025",
    wordCount: 2313,
  },
  {
    id: "benjamin-parry-2023",
    url: "https://benparry.substack.com/p/2023-annual-letter",
    year: 2023,
    author: "Benjamin Parry",
    title: "2023 Annual Letter",
    preview: "Year in review and aims for 2024",
    wordCount: 1855,
  },
  {
    id: "benjamin-parry-2022",
    url: "https://benparry.substack.com/p/2022-annual-letter",
    year: 2022,
    author: "Benjamin Parry",
    title: "2022 Annual Letter",
    preview: "Year in review and aims for 2023",
    wordCount: 1756,
  },
  {
    id: "benjamin-parry-2021",
    url: "https://benparry.substack.com/p/2021-letter",
    year: 2021,
    author: "Benjamin Parry",
    title: "2021 Annual Letter",
    preview: "Year in review and aims for 2022",
    wordCount: 1821,
  },
  {
    id: "craig-shapiro-2025",
    url: "https://collabfund.substack.com/p/2025-year-in-review",
    year: 2025,
    author: "Craig Shapiro",
    title: "Collaborative Fund 2025 Year in Review",
    preview:
      "A year of unlikely investments, long-term bets, and new beginnings.",
    wordCount: 533,
  },
  {
    id: "justin-jackson-2021",
    url: "https://justinjackson.ca/2021-review",
    year: 2021,
    author: "Justin Jackson",
    title: "2021 year in review",
    preview:
      "Justin Jackson's annual review: personal update, business, community",
    wordCount: 1509,
  },
  {
    id: "jimzub-2024",
    url: "https://www.jimzub.com/zubby-newsletter-95-year-in-review/",
    year: 2024,
    author: "Jim Zub",
    title: "Zubby Newsletter #95: Year In Review | Zub Tales",
    preview:
      "For the past 14 years I’ve been putting together a ‘Year In Review‘ post on my website as a way to summarize my thoughts and feelings on the year that was. It’s nice to measure highs and lows, and help jog my memory as things carry forward.",
    wordCount: 2307,
  },
  {
    id: "jimzub-2023",
    url: "https://www.jimzub.com/year-in-review-13/",
    year: 2023,
    author: "Jim Zub",
    title: "Zubby Newsletter #42: Year In Review, 2023 | Zub Tales",
    preview:
      "For the past 13 years I’ve been putting together a ‘Year In Review‘ post on my website as a way to summarize my thoughts and feelings on the year that was. It’s a nice way to measure highs and lows, and help jog my memory as things carry forward.",
    wordCount: 2096,
  },
  {
    id: "jimzub-2022",
    url: "https://www.jimzub.com/year-in-review-12/",
    year: 2022,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Last year I wrote that 2021 felt like a vortex, eating up time as we wondered when things would get better. 2022 showed some respite from the lows I felt over the past two years and it was a return to more in-person interaction, but it’s still hard to say if any of this is “normal.”",
    wordCount: 1683,
  },
  {
    id: "jimzub-2021",
    url: "https://www.jimzub.com/year-in-review-11/",
    year: 2021,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "While doing some year-end financial calculations yesterday I filled out an entire excel spreadsheet, dozens of dated entries, and made every single one a 2020 date instead of 2021.",
    wordCount: 1692,
  },
  {
    id: "jimzub-2020",
    url: "https://www.jimzub.com/year-in-review-10/",
    year: 2020,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Here we go again. A post to try and summarize the year that was and, man oh man, 2020 was quite possibly the strangest of them all.",
    wordCount: 1748,
  },
  {
    id: "jimzub-2019",
    url: "https://www.jimzub.com/year-in-review-9/",
    year: 2019,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "As I’ve done in years past, I try to sum up the year that was in a post here on my site. 2019 had some of the highest highs and lowest lows in recent memory, closing out the decade in ways I never could have imagined.",
    wordCount: 1840,
  },
  {
    id: "jimzub-2018",
    url: "https://www.jimzub.com/year-in-review-8/",
    year: 2018,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "I’ve been writing these ‘Year In Review’ posts since 2010, and each time I try to summarize what’s happening in my life and the gratitude I have for all these incredible experiences.",
    wordCount: 1983,
  },
  {
    id: "jimzub-2017",
    url: "https://www.jimzub.com/year-in-review-7/",
    year: 2017,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "As I’ve done in years past, I try to sum up the year that was in a post here on my site. 2017 was a strong year for me on a personal level and that felt a bit odd compared to the tumultuous and difficult state of the world at large.",
    wordCount: 2047,
  },
  {
    id: "jimzub-2016",
    url: "https://www.jimzub.com/year-in-review-6/",
    year: 2016,
    author: "Jim Zub",
    title: "Year in Review | Zub Tales",
    preview:
      "As I’ve done in years past, I try to use this post to sum up the year that was. 2016 was such a strange and turbulent time around the world and that made it even more surreal as I personally had a banner year in my work and personal life.",
    wordCount: 1787,
  },
  {
    id: "jimzub-2015",
    url: "https://www.jimzub.com/year-in-review-5/",
    year: 2015,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Here we go again, a look at my year in review. I’ve been doing this on my blog for the past few years (2010, 2011, 2012, 2013, 2014). It’s a nice way to sum up my thoughts on the year that was and take in the ups and downs that came with it.",
    wordCount: 2201,
  },
  {
    id: "jimzub-2014",
    url: "https://www.jimzub.com/year-in-review-4/",
    year: 2014,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Here we go again, a look at my year in review. I’ve been doing this on my blog for the past few years (2010, 2011, 2012, 2013) and it’s a nice way to sum up my thoughts on the year that was and take in the ups and downs that came with it.",
    wordCount: 2214,
  },
  {
    id: "jimzub-2013",
    url: "https://www.jimzub.com/2013-a-great-year-that-almost-wasnt/",
    year: 2013,
    author: "Jim Zub",
    title: "2013 – A Great Year That Almost Wasn’t | Zub Tales",
    preview:
      "2013 has been an incredible year, but it sure as heck didn’t start out that way.",
    wordCount: 2136,
  },
  {
    id: "jimzub-2012",
    url: "https://www.jimzub.com/year-in-review-3/",
    year: 2012,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "It’s time again for my year in review post. I’ve been doing this for the past three years, looking backwards and forwards, trying to gauge where things have been, where they are now and where I’d like them to be in the year ahead.",
    wordCount: 2041,
  },
  {
    id: "jimzub-2011",
    url: "https://www.jimzub.com/year-in-review-2/",
    year: 2011,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Almost a year ago to the day I posted up a Year In Review for 2010 with thoughts on how the year had gone and intentions for 2011. 12 months later, I’m here to see how that went and do it again.",
    wordCount: 2468,
  },
  {
    id: "jimzub-2010",
    url: "https://www.jimzub.com/year-in-review/",
    year: 2010,
    author: "Jim Zub",
    title: "Year In Review | Zub Tales",
    preview:
      "Some times I get a chance to bang out thoughts on the year that was, but I don’t do it as often as I should. So, here goes…",
    wordCount: 1890,
  },
];
