import { YearInReviewPost } from "./types";

export const posts: YearInReviewPost[] = [
  // Dan Wang posts
  {
    id: "danwang-2025",
    url: "https://danwang.co/2025-letter/",
    year: 2025,
    author: "Dan Wang",
    title: "2025 Letter",
    preview:
      "Corgis, compute, Cold War; Ecclesiastes; ties; Stendhal; humor; Pascal's Wager; deep infrastructure; Germanic obedience; Texas State Fair",
    wordCount: 17358,
  },
  {
    id: "danwang-2023",
    url: "https://danwang.co/2023-letter/",
    year: 2023,
    author: "Dan Wang",
    title: "2023 Letter",
    preview:
      "A walk-and-talk; Crumb; running and tangping; Knausgaard; Elon as Palmer Eldritch; memelords; Chicago as a megacity; Norton; and a pause.",
    wordCount: 10865,
  },
  {
    id: "danwang-2022",
    url: "https://danwang.co/2022-letter/",
    year: 2022,
    author: "Dan Wang",
    title: "2022 Letter",
    preview:
      "Becoming a barbarian; an ideological revelry; lockdown; sweetgrass and banana leafs; crankiness; delightful animals; to the mountains",
    wordCount: 12400,
  },
  {
    id: "danwang-2021",
    url: "https://danwang.co/2021-letter/",
    year: 2021,
    author: "Dan Wang",
    title: "2021 Letter",
    preview:
      "Getting worse and getting better; Jesuits; common prosperity; Rossini's glittering realm; slow-casual chains; Lem's ocean; vowelsongs.",
    wordCount: 18734,
  },
  {
    id: "danwang-2020",
    url: "https://danwang.co/2020-letter/",
    year: 2020,
    author: "Dan Wang",
    title: "2020 Letter",
    preview:
      "Centralized campaigns of inspiration; Proust; rejecting complacency and decadence; the pandemic in Beijing; brown sauce; riding a bike; rejuvenation.",
    wordCount: 11660,
  },
  // Andrej Karpathy posts
  {
    id: "karpathy-2025",
    url: "https://karpathy.bearblog.dev/year-in-review-2025/",
    year: 2025,
    author: "Andrej Karpathy",
    title: "Year in Review 2025",
    preview: "2025 Year in Review of LLM paradigm changes",
    wordCount: 1908,
  },
  // Simon Willison posts
  {
    id: "simonwillison-2025",
    url: "https://simonwillison.net/2025/Dec/31/the-year-in-llms/",
    year: 2025,
    author: "Simon Willison",
    title: "The Year in LLMs",
    preview:
      "This is the third in my annual series reviewing everything that happened in the LLM space over the past 12 months. For previous years see Stuff we figured out about …",
    wordCount: 8224,
  },
  {
    id: "simonwillison-2024",
    url: "https://simonwillison.net/2024/Dec/31/llms-in-2024/",
    year: 2024,
    author: "Simon Willison",
    title: "LLMs in 2024",
    preview:
      "A lot has happened in the world of Large Language Models over the course of 2024. Here’s a review of things we figured out about the field in the past …",
    wordCount: 7601,
  },
  {
    id: "simonwillison-2023",
    url: "https://simonwillison.net/2023/Dec/31/ai-in-2023/",
    year: 2023,
    author: "Simon Willison",
    title: "AI in 2023",
    preview:
      "2023 was the breakthrough year for Large Language Models (LLMs). I think it’s OK to call these AI—they’re the latest and (currently) most interesting development in the academic field of …",
    wordCount: 3511,
  },
  {
    id: "zvi-mowshowitz-2025",
    url: "https://thezvi.substack.com/p/2025-year-in-review",
    year: 2025,
    author: "Zvi Mowshowitz",
    title: "2025 Year in Review",
    preview: "It’s that time.",
    wordCount: 3978,
  },
  {
    id: "nate-silver-2025",
    url: "https://substack.com/home/post/p-183079902?source=queue",
    year: 2025,
    author: "Nate Silver",
    title: "The Silver Bulletin Year in Review",
    preview:
      "My favorite posts of 2025, some notes on the business, and a thank you to our readers.",
    wordCount: 3949,
  },
  {
    id: "jim-zub-2025",
    url: "https://jimzub.substack.com/p/zubby-newsletter-140-year-in-review",
    year: 2025,
    author: "Jim Zub",
    title: "Zubby Newsletter #140: Year In Review",
    preview:
      "For the past 15 years I’ve put together a ‘Year In Review‘ post on my website as a way to summarize my thoughts and feelings on the year that was.",
    wordCount: 1024,
  },
  {
    id: "michael-mcfaul-2025",
    url: "https://michaelmcfaul.substack.com/p/mcfauls-world-2025-year-in-review",
    year: 2025,
    author: "Michael McFaul",
    title: "McFaul’s World — 2025 Year in Review",
    preview: "Looking back on a turbulent year.",
    wordCount: 1427,
  },
  {
    id: "nathan-lambert-2025",
    url: "https://substack.com/home/post/p-181486818?source=queue",
    year: 2025,
    author: "Nathan Lambert",
    title: "2025 Interconnects year in review",
    preview: "Three years writing every week about AI.",
    wordCount: 2049,
  },
  {
    id: "noah-smith-2025",
    url: "https://www.noahpinion.blog/p/noahpinions-2025-year-in-review?triedRedirect=true",
    year: 2025,
    author: "Noah Smith",
    title: "Noahpinion's 2025 Year in Review",
    preview: "Year Five of the Noahpinion Substack.",
    wordCount: 3164,
  },
  {
    id: "janelle-teng-wade-2024",
    url: "https://nextbigteng.substack.com/p/2024-year-in-review-2025-predictions",
    year: 2024,
    author: "Janelle Teng Wade",
    title: "2024 Year-In-Review + 2025 Predictions",
    preview:
      "In this last post of the year, I look back at five of the biggest B2B AI & software debates in 2024, and preview what 2025 may have in store for us.",
    wordCount: 1841,
  },
  {
    id: "james-stanier-2024",
    url: "https://theengineeringmanager.substack.com/p/2024-the-year-in-review",
    year: 2024,
    author: "James Stanier",
    title: "2024: the year in review",
    preview: "Efficiency, optimism, and not getting left behind.",
    wordCount: 2648,
  },
  {
    id: "matthew-long-2024",
    url: "https://matthewmlong.substack.com/p/2024-year-in-review",
    year: 2024,
    author: "Matthew Long",
    title: "2024 Year-in-Review",
    preview: "In which I share my reading journey for 2024",
    wordCount: 679,
  },
  {
    id: "connor-swenson-2024",
    url: "https://onepercentwisdom.substack.com/p/2024-annual-review",
    year: 2024,
    author: "Connor Swenson",
    title: "2024 Annual Review",
    preview: "The Year of Kaia",
    wordCount: 3941,
  },
  {
    id: "phillips-p-obrien-2024",
    url: "https://phillipspobrien.substack.com/p/2024-year-in-review-part-1",
    year: 2024,
    author: "Phillips P. OBrien",
    title: "2024 Year in Review: Part 1",
    preview: "How Historians Might Write the Russo-Ukraine War.",
    wordCount: 238,
  },
  {
    id: "jarrett-fuller-2024",
    url: "https://jarrettfuller.substack.com/p/38-a-2024-year-in-review",
    year: 2024,
    author: "Jarrett Fuller",
    title: "38. A 2024 Year in Review",
    preview: "Happy new year!",
    wordCount: 1523,
  },
  {
    id: "mischa-willett-2024",
    url: "https://mischawillett.substack.com/p/year-in-review-2024",
    year: 2024,
    author: "Mischa Willett",
    title: "Year in Review 2024",
    preview: "'I will build a boat in the desert place'",
    wordCount: 866,
  },
  {
    id: "cl-kao-2023",
    url: "https://clkao.substack.com/p/2023-year-in-review",
    year: 2023,
    author: "CL Kao",
    title: "2023 Year In Review",
    preview: "The Geekway, and may we all focus on what is meaningful",
    wordCount: 321,
  },
  {
    id: "michael-mcfaul-2023",
    url: "https://michaelmcfaul.substack.com/p/mcfauls-world-2023-year-in-review",
    year: 2023,
    author: "Michael McFaul",
    title: "McFaul’s World – 2023 Year in Review",
    preview: "Hoping for a more peaceful 2024!",
    wordCount: 1772,
  },
  {
    id: "daniel-bashir-2023",
    url: "https://thegradientpub.substack.com/p/a-year-in-review-2023",
    year: 2023,
    author: "daniel bashir",
    title: "A Year in Review: 2023",
    preview: "A thank you, and a reminder about our mission",
    wordCount: 1308,
  },
  {
    id: "nathan-lambert-2024",
    url: "https://www.interconnects.ai/p/2024-interconnects-year-in-review",
    year: 2024,
    author: "Nathan Lambert",
    title: "2024 Interconnects year in review",
    preview: "Two years writing every week on AI.",
    wordCount: 1813,
  },
  {
    id: "nathan-lambert-2023",
    url: "https://www.interconnects.ai/p/2023-review",
    year: 2023,
    author: "Nathan Lambert",
    title: "Interconnects year in review: 2023",
    preview:
      "The core themes of ML and the blog this year. What changes in 2024.",
    wordCount: 2486,
  },
  {
    id: "nathan-lambert-2020",
    url: "https://www.interconnects.ai/p/2020",
    year: 2020,
    author: "Nathan Lambert",
    title: "Democratizing Automation 2020: (half) year in review",
    preview:
      "How I ended up with 26 posts in my first half year of weekly writing. What we learned and where we are going.",
    wordCount: 1228,
  },
  {
    id: "janelle-teng-wade-2025",
    url: "https://nextbigteng.substack.com/p/2025-year-in-review-ai-bubble-or-breakthrough",
    year: 2025,
    author: "Janelle Teng Wade",
    title: "2025 Year-In-Review: AI Bubble or Breakthrough?",
    preview:
      "From power-law breakouts to bubble concerns, my final post of 2025 takes a retrospective look at the most consequential AI debates of the year and examines what these signals may reveal for 2026.",
    wordCount: 1312,
  },
  {
    id: "janelle-teng-wade-2024-2",
    url: "https://nextbigteng.substack.com/p/saasy-predictions-for-2024",
    year: 2024,
    author: "Janelle Teng Wade",
    title: "SaaSy Predictions for 2024",
    preview:
      "In every last post of the year, I reflect on notable events from the past 12 months & offer predictions on the next big thing for the new year. Trigger warning for 2024: a lot more AI content ahead...",
    wordCount: 2153,
  },
  {
    id: "janelle-teng-wade-2023",
    url: "https://nextbigteng.substack.com/p/saasy-predictions-for-2023",
    year: 2023,
    author: "Janelle Teng Wade",
    title: "SaaSy Predictions for 2023",
    preview:
      "In this final post of 2022, I revisit notable events which have defined this tumultuous year for cloud companies and offer some predictions on what the next big thing in SaaS might look like in 2023.",
    wordCount: 1772,
  },
  {
    id: "connor-swenson-2023",
    url: "https://onepercentwisdom.substack.com/p/2023-in-review-ola-portugal",
    year: 2023,
    author: "Connor Swenson",
    title: "2023 In Review: Olá, Portugal!",
    preview: "My 2023 Personal Annual Review",
    wordCount: 2237,
  },
  {
    id: "connor-swenson-2021",
    url: "https://onepercentwisdom.substack.com/p/14103661_one-percent-wisdom-2021-annual-review-jan-13-2022",
    year: 2021,
    author: "Connor Swenson",
    title: "Annual Review 2021 | #68",
    preview: "One Percent Wisdom",
    wordCount: 413,
  }
];
